name: custom_date
description: Contains code to deal with only date objects without time to support swagger.
version: 1.0.0
homepage: https://github.com/sridhar562345/date.git

environment:
  sdk: '>=2.15.1 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
